In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
%matplotlib inline

In [2]:
data = pd.read_csv('Titanic Dataset/train.csv')
data1 = pd.read_csv('Titanic Dataset/test.csv')
yTest = pd.read_csv('Titanic Dataset/sample_submission.csv')


In [3]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:

for i in range(len(data['Sex'].values)):
    if data['Sex'].values[i]=="male":
        data['Sex'].values[i]=0
    else:
        data['Sex'].values[i]=1
    if data['Age'].values[i]==np.NaN:
        data['Age'].values[i]=0

data['Age'].fillna(data['Age'].mean(), inplace=True)


data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris   0  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.000000      1   
2                               Heikkinen, Miss. Laina   1  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.000000      1   
4                             Allen, Mr. William Henry   0  35.000000      0   
..                                                 ...  ..        ...    ...   
886                              Montvila, Rev. Juozas   0  27.000000      0   
887                       Graham, Miss. Margaret Edith   1  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"   1  29.699118      1   
889                              Behr, Mr. Karl Howell   0  26.000000      0   
890                                Dooley, Mr. Patrick   0  32.000000      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:

for i in range(len(data1['Sex'].values)):
    if data1['Sex'].values[i]=="male":
        data1['Sex'].values[i]=0
    else:
        data1['Sex'].values[i]=1
mean_age=0.0
mean_fair=0.0

data1['Age'].fillna(data1['Age'].mean(), inplace=True)

data1['Fare'].fillna(data1['Fare'].mean(), inplace=True)


data1

PassengerId  Pclass                                          Name Sex  \
0            892       3                              Kelly, Mr. James   0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   1   
2            894       2                     Myles, Mr. Thomas Francis   0   
3            895       3                              Wirz, Mr. Albert   0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   1   
..           ...     ...                                           ...  ..   
413         1305       3                            Spector, Mr. Woolf   0   
414         1306       1                  Oliva y Ocana, Dona. Fermina   1   
415         1307       3                  Saether, Mr. Simon Sivertsen   0   
416         1308       3                           Ware, Mr. Frederick   0   
417         1309       3                      Peter, Master. Michael J   0   

          Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0    34.50000      0      0              330911    7.8292   NaN        Q  
1    47.00000      1      0              363272    7.0000   NaN        S  
2    62.00000      0      0              240276    9.6875   NaN        Q  
3    27.00000      0      0              315154    8.6625   NaN        S  
4    22.00000      1      1             3101298   12.2875   NaN        S  
..        ...    ...    ...                 ...       ...   ...      ...  
413  30.27259      0      0           A.5. 3236    8.0500   NaN        S  
414  39.00000      0      0            PC 17758  108.9000  C105        C  
415  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416  30.27259      0      0              359309    8.0500   NaN        S  
417  30.27259      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
data.Survived.values.shape

(891,)

In [10]:
X_train, X_test, y_train, y_test = data.loc[:,["Pclass","Sex","Age","SibSp","Parch","Fare"]].values,data1.loc[:,["Pclass","Sex","Age","SibSp","Parch","Fare"]].values,data.Survived.values,yTest.Survived.values

In [11]:

print('Train - Predictors shape', X_train.shape)
print('Test - Predictors shape', X_test.shape)
print('Train - Target shape', y_train.shape)
print('Test - Target shape', y_test.shape)


Train - Predictors shape (891, 6)
Test - Predictors shape (418, 6)
Train - Target shape (891,)
Test - Target shape (418,)


In [12]:
X_train = np.reshape(X_train, (-1,6))
X_test = np.reshape(X_test, (-1,6))
y_train = np.reshape(y_train, (-1,1))
y_test = np.reshape(y_test, (-1,1))

In [13]:

print('Train - Predictors shape', X_train.shape)
print('Test - Predictors shape', X_test.shape)
print('Train - Target shape', y_train.shape)
print('Test - Target shape', y_test.shape)


Train - Predictors shape (891, 6)
Test - Predictors shape (418, 6)
Train - Target shape (891, 1)
Test - Target shape (418, 1)


In [14]:
model.fit(X_train, y_train)

/Users/bhavikmangla/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [15]:
model.score(X_test, y_test)

0.9449760765550239

In [16]:
model.predict(X_test)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [17]:
y_predicted = model.predict(X_test)

In [18]:
def sigmoid(z):
  return 1.0 / (1 + np.exp(-z))

In [19]:
def predict(features, weights):
  '''
  Returns 1D array of probabilities
  that the class label == 1
  '''
  z = np.dot(features, weights)
  return sigmoid(z)

In [21]:
def cost_function(features, labels, weights):
    '''
    Cost = (labels*log(predictions) + (1-labels)*log(1-predictions) ) / len(labels)
    '''
    observations = len(labels)

    predictions = predict(features, weights)

    #Take the error when label=1
    class1_cost = -labels*np.log(predictions)

    #Take the error when label=0
    class2_cost = (1-labels)*np.log(1-predictions)

    #Take the sum of both costs
    cost = class1_cost - class2_cost

    #Take the average cost
    cost = cost.sum() / observations

    return cost

In [22]:
theta = np.array([1,1,1,1,1,1]).reshape(-1,1)

In [23]:
def update_weights(features, labels, weights, lr):
    '''
    Vectorized Gradient Descent
    '''
    N = len(features)
    
    predictions = predict(features, weights)

    gradient = np.dot(features.T,  predictions - labels)
    gradient /= N
    gradient *= lr

    weights -= gradient

    return weights

In [24]:
def decision_boundary(prob):
  return 1 if prob >= .5 else 0

In [25]:
def classify(predictions):
  '''
  input  - N element array of predictions between 0 and 1
  output - N element array of 0s (False) and 1s (True)
  '''
  arr=[]
  for i in predictions:
    arr.append(decision_boundary(i))
  return arr

In [26]:
def train(features, labels, weights, lr, iters):
    cost_history = []

    for i in range(iters):
        weights = update_weights(features, labels, weights, lr)

        #Calculate error for auditing purposes
        cost = cost_function(features, labels, weights)
        cost_history.append(cost)


    return weights, cost_history

In [27]:
w, c_history = train(X_train.astype(float),y_train.astype(float),theta.astype(float),0.001,100000)

/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_6824/735946531.py:13: RuntimeWarning: divide by zero encountered in log
  class2_cost = (1-labels)*np.log(1-predictions)
/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_6824/735946531.py:13: RuntimeWarning: invalid value encountered in multiply
  class2_cost = (1-labels)*np.log(1-predictions)


In [28]:
w

array([[-0.53189604],
       [ 2.68126147],
       [-0.01527813],
       [-0.30873789],
       [-0.12901331],
       [ 0.00898873]])

In [29]:
result_y = predict(X_test.astype(float), w.astype(float))

In [30]:
len(classify(result_y))

418

In [31]:
yTest.Survived.values

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [32]:
arr = np.array(classify(result_y))
arr.reshape(1,-1)

array([[0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 

In [33]:
test_data_accuracy = accuracy_score(y_test, arr)

In [34]:
test_data_accuracy

0.9736842105263158